### ISSUE TITLE
[Feature Request] User expects to hear the entered name once agent is connected

### ISSUE THREAD

**Issue by cyfyifanchen** [TEN-framework/TEN-Agent#15]

**Comment by wangyoucao577** [comment]
<img width="445" alt="image" src="https://github.com/user-attachments/assets/30c093fe-71fd-4736-8ca1-3dcfa4aa5826">

Replace the `User Name` to `What should ASTRA agents call you?` seems better? once the feature is ready.

**Comment by cyfyifanchen** [comment]
Excellent observation, let's do that.

**Comment by cyfyifanchen** [comment]
We've got rid of the entering name page for playground.
