### ISSUE TITLE
[Bug][DX] Docker compose logging shows wrong port for graph designer.

### ISSUE THREAD

**Issue by cyfyifanchen** [TEN-framework/TEN-Agent#164]
<img width="645" alt="image" src="https://github.com/user-attachments/assets/dd421c8f-9030-4db9-b17b-4929314aee9b">

**Comment by cyfyifanchen** [comment]
Which should be 3001.

**Comment by cyfyifanchen** [comment]
I almost forget that by default NextJS automatically increase 1 if port 3000 is taken.

**Comment by plutoless** [comment]
the port is 3000 inside the container while it's mapped to 3001 by docker. so this is expected.
