### ISSUE TITLE
After deployment, multiple computers cannot call the camera

### ISSUE THREAD

**Issue by Sam-SSTU** [TEN-framework/TEN-Agent#213]
部署完成后多台电脑无法调用本机摄像头，插入外接摄像头后刷新界面，两个摄像头就都可以读取了，再拔掉外接摄像头，就可以调用本机摄像头了

After the deployment is complete, multiple computers cannot call the local camera. After plugging in the external camera and refreshing the interface, both cameras can be read. Then unplug the external camera and you can call the local camera.

怀疑是浏览器或者系统的问题，都是Win11+chrome内核
I suspect it's a browser or system problem, which both are Win11+chrome kernel

**Comment by plutoless** [comment]
never reproduced. maybe try again to see if it's fixed.
