### ISSUE TITLE
Can the language of astra voice agent be changed automatically according to the output language?

### ISSUE THREAD

**Issue by Sam-SSTU** [TEN-framework/TEN-Agent#214]
add an auto-detect button here?
![image](https://github.com/user-attachments/assets/0c605c5a-ed16-454e-a67c-551ace692398)

**Comment by cyfyifanchen** [comment]
It kinda does right now, but it needs further tuning to achieve gpt-liked style.

**Comment by plutoless** [comment]
https://github.com/TEN-framework/TEN-Agent/pull/338
