### ISSUE TITLE
Text output in astra voice agent has a limit

### ISSUE THREAD

**Issue by Sam-SSTU** [TEN-framework/TEN-Agent#216]
![image](https://github.com/user-attachments/assets/5d2df99f-e524-4229-83e3-d73b9d60132b)

windows11+docker

**Comment by cyfyifanchen** [comment]
@Sam-SSTU Sam, let’s make this international by translating everything into English for contributors who aren’t as familiar with Mandarin as you are.

**Comment by Sam-SSTU** [comment]
> @Sam-SSTU Sam, let’s make this international by translating everything into English for contributors who aren’t as familiar with Mandarin as you are.

fixed

**Comment by plutoless** [comment]
fixed in latest version
