### ISSUE TITLE
[Feature Request] azure openai support 

### ISSUE THREAD

**Issue by wangyoucao577** [TEN-framework/TEN-Agent#270]
https://techcommunity.microsoft.com/t5/startups-at-microsoft/migrating-from-openai-to-azure-openai/ba-p/3989463

Azure's OpenAI usage is slightly different than OpenAI's. It's better to support them both.

**Comment by ZJJHYM** [comment]
hello, how to use Azure's OpenAI in this project?Are there any steps that can be taught?

**Comment by plutoless** [comment]
@ZJJHYM you just need to use openai's extension, and set path/vendor/base_uri properties
