### ISSUE TITLE
change the script so that we can work on a local run on macbook

### ISSUE THREAD

**Issue by syangdh** [TEN-framework/TEN-Agent#290]
I followed the instruction to Step 4, and `make build` inside the container gives the following error message. (I am using a M2 chip Macbook), can you suggest how to play with this on macbook?

root@fb5e1a2062f4:/app# make build
>> build agents
cd agents && ./scripts/install_deps_and_build.sh mac arm64 && mv bin/main bin/worker
./scripts/install_deps_and_build.sh: line 91:    98 Illegal instruction     /tmp/test
FATAL: unsupported platform.
       Please UNCHECK the 'Use Rosetta for x86_64/amd64 emulation on Apple Silicon' Docker Desktop setting if you're running on mac.
make: *** [Makefile:11: build-agents] Error 1
root@fb5e1a2062f4:/app# vi agents/scripts/install_deps_and_build.sh

**Comment by cyfyifanchen** [comment]
Hi @syangdh, you need to uncheck this box if you are on Apple Silicon.
<img width="850" alt="image" src="https://github.com/user-attachments/assets/78648529-dbd0-4782-95a3-c64156aaadf6">

**Comment by cyfyifanchen** [comment]
Feel free to reopen the issue if the problem persists.
