### ISSUE TITLE
[Bug] long transcribe display problem

### ISSUE THREAD

**Issue by seven1240** [TEN-framework/TEN-Agent#296]
**Is your feature request related to a problem? Please describe.**

when the TTS returns long sentence, it only shows the first part, but the audio is complete. and after the audio is done, keep talking will cause the displayed part gone, it is reproducable.

I use Female, Chinese, and the voice agent - OpenAI LLM + Azure TTS (not the camera one).

See attached.

pic1: it displayed the first part until: 热情的人们（逗号）

![8731727588985_ pic](https://github.com/user-attachments/assets/ebdc3880-7104-42ff-9203-e5bd62f270b1)

pic2: the 热情的人们 part was gone.

![8741727588987_ pic](https://github.com/user-attachments/assets/9dd67719-dd05-458b-b4d3-8871f714f40a)

**Comment by plutoless** [comment]
fixed.
