### ISSUE TITLE
I'd like to know how to swap out a specific API for a locally fine-tuned model

### ISSUE THREAD

**Issue by whyshifht** [TEN-framework/TEN-Agent#349]
As the title suggests, I looked at some of the code in the project, but I didn't see the possibility of replacing it with a local model

**Comment by wangyoucao577** [comment]
What you can do it to implement a new extension similar with the `openai_chatgpt_python`, the only difference is that `openai_chatgpt_python` accesses openai's service but your extension initializes and runs local modes. Here's a quick tutorial, FYI https://doc.theten.ai/tutorials/how_to_run_local_model_in_python_extensions
