### ISSUE TITLE
Why didn't I change the local code and then start without any changes?

### ISSUE THREAD

**Issue by whyshifht** [TEN-framework/TEN-Agent#350]
I modified the opening sentence in my local TEN-Agent-main/demo/srcapp/api/agents/start/graph.tsx file, but it doesn't work, please help!

**Comment by wangyoucao577** [comment]
What do you mean of `opening sentence` and what do you want to achieve?

**Comment by cyfyifanchen** [comment]
@whyshifht bro probably is talking about the greetings, you can do that either in GD(Graph designer) or `property.json`.

**Comment by cyfyifanchen** [comment]
@whyshifht Feel free to reopen if the issue persists.
