### ISSUE TITLE
Server报错

### ISSUE THREAD

**Issue by conan0267** [TEN-framework/TEN-Agent#391]
2024/11/10 07:49:46 INFO handlerPing start channelName=agora_pyu5xu requestId=9e987b70-07d3-461b-9f08-f6a78316afe5 service=HTTP_SERVER
2024/11/10 07:49:46 ERROR handlerPing channel not existed channelName=agora_pyu5xu requestId=9e987b70-07d3-461b-9f08-f6a78316afe5 service=HTTP_SERVER

**Comment by jatmeibo** [comment]
我也遇到了同样的问题，.env配置文件中我只配置了AGORA_APP_ID、OPENAI_API_KEY这2个参数，进入localhost:3002后，点击connect后，make run-server启动的服务日志中就报错：
`[GIN] 2024/11/11 - 01:43:15 | 200 |     161.638µs |      172.18.0.1 | POST     "/ping"
2024/11/11 01:43:18 INFO handlerPing start channelName=agora_sa8uf1 requestId=7bc8e64c-e7a6-4e55-8fb3-d6b2a636fd22 service=HTTP_SERVER
2024/11/11 01:43:18 ERROR handlerPing channel not existed channelName=agora_sa8uf1 requestId=7bc8e64c-e7a6-4e55-8fb3-d6b2a636fd22 service=HTTP_SERVER
[GIN] 2024/11/11 - 01:43:18 | 200 |     162.516µs |      172.18.0.1 | POST     "/ping"
2024/11/11 01:43:21 INFO handlerPing start channelName=agora_sa8uf1 requestId=bd266773-b35d-4da9-91fd-6fc837cd0f43 service=HTTP_SERVER
2024/11/11 01:43:21 ERROR handlerPing channel not existed channelName=agora_sa8uf1 requestId=bd266773-b35d-4da9-91fd-6fc837cd0f43 service=HTTP_SERVER
[GIN] 2024/11/11 - 01:43:21 | 200 |      201.58µs |      172.18.0.1 | POST     "/ping"
2024/11/11 01:43:22 INFO handlerStop start req="{RequestId:c3e5e032-4c77-486e-aa6a-2244542a1a3f ChannelName:agora_sa8uf1}" service=HTTP_SERVER
2024/11/11 01:43:22 ERROR handlerStop channel not existed channelName=agora_sa8uf1 requestId=c3e5e032-4c77-486e-aa6a-2244542a1a3f service=HTTP_SERVER`

**Comment by cyfyifanchen** [comment]
#395 The icon at top right corner indicates the quality of the network, it actually has nothing todo with the connection to TEN Agent, we are thinking about getting rid of it.

**Comment by Michael-Nan1** [comment]
> ## 我也遇到了同样的问题，.env配置文件中我只配置了AGORA_APP_ID、OPENAI_API_KEY这2个参数，进入localhost：3002后，点击connect后，make run-server启动的服务日志中就报错：
> `[GIN] 2024/11/11 - 01:43:15 | 200 | 161.638µs | 172.18.0.1 | POST "/ping" 2024/11/11 01:43:18 INFO handlerPing start channelName=agora_sa8uf1 requestId=7bc8e64c-e7a6-4e55-8fb3-d6b2a636fd22 service=HTTP_SERVER 2024/11/11 01:43:18 ERROR handlerPing channel not existed channelName=agora_sa8uf1 requestId=7bc8e64c-e7a6-4e55-8fb3-d6b2a636fd22 service=HTTP_SERVER [GIN] 2024/11/11 - 01:43:18 | 200 | 162.516µs | 172.18.0.1 | POST "/ping" 2024/11/11 01:43:21 INFO handlerPing start channelName=agora_sa8uf1 requestId=bd266773-b35d-4da9-91fd-6fc837cd0f43 service=HTTP_SERVER 2024/11/11 01:43:21 ERROR handlerPing channel not existed channelName=agora_sa8uf1 requestId=bd266773-b35d-4da9-91fd-6fc837cd0f43 service=HTTP_SERVER [GIN] 2024/11/11 - 01:43:21 | 200 | 201.58µs | 172.18.0.1 | POST "/ping" 2024/11/11 01:43:22 INFO handlerStop start req="{RequestId:c3e5e032-4c77-486e-aa6a-2244542a1a3f ChannelName:agora_sa8uf1}" service=HTTP_SERVER 2024/11/11 01:43:22 ERROR handlerStop channel not existed channelName=agora_sa8uf1 requestId=c3e5e032-4c77-486e-aa6a-2244542a1a3f service=HTTP_SERVER`
> 另外，进入localhost：3002后，页面右上角信号图标一直是不可用状态

Do you solve this problem?

**Comment by cyfyifanchen** [comment]
Channel not existed, looks like server isn't running right, kill it and restart to try.
