### ISSUE TITLE
Adding TEN Framework logo top left corner

### ISSUE THREAD

**Issue by cyfyifanchen** [TEN-framework/TEN-Agent#406]
<img width="2031" alt="image" src="https://github.com/user-attachments/assets/021b1bc9-8152-489b-adca-aa854ce63c44">

1. Adding TEN Framework logo that links to TEN Framework repo(https://github.com/ten-framework/ten_framework)
2. Adding padding 20 - 30 px
3. Removing network quality and color palette. 
4. Removing Channel name.

**Comment by cyfyifanchen** [comment]
![white-w-title](https://github.com/user-attachments/assets/c1ebcce5-aca0-4e45-b9c4-305f5b5e21dd)

Logo is here.

**Comment by cyfyifanchen** [comment]
Hi, @gauravnadkarni thank you for your interest. There is currently a PR being worked on, which has a little UI lifting affecting this page right now. I'd recommend waiting for that PR to be merged before proceeding. 

Once it's done, I will provide more detailed info. Thanks in advance for your contribution.

**Comment by gauravnadkarni** [comment]
@cyfyifanchen Thanks for the heads-up. I'll wait for further update on this.

**Comment by cyfyifanchen** [comment]
@gauravnadkarni hey sorry for the wait, been busy, are you still interested? I think there is a sample task to remove letter U avatar out of the conversation menu, apparently someone else is working on that, but haven't seen the PR for a long time, I bet you could take on the task and make it happen.

**Comment by gauravnadkarni** [comment]
Hi @cyfyifanchen, No Problem! Sure, I can look into that. I believe you are referring to the following issue: https://github.com/TEN-framework/TEN-Agent/issues/407. Per my understanding, I have to get rid of the Avatar "U" that appears besides the message. 
Please assign that issue to me.

**Comment by cyfyifanchen** [comment]
@gauravnadkarni dope, go ahead work on it. Thanks for your contribution.  It, for some reasons, doesn't let me assign it anyone out of the suggestion list.
