### ISSUE TITLE
[BUG] color picker is not working

### ISSUE THREAD

**Issue by plutoless** [TEN-framework/TEN-Agent#409]
### Description

color picker is not working on demo/playground

### Environment

linux

### Steps to reproduce

1. choose any color in demo/playground

### Expected behavior

the color picker should be working

### Severity

Major

### Additional Information

![Screenshot 2024-11-13 at 09 29 09](https://github.com/user-attachments/assets/fd9c485d-1620-4a9a-9c73-51c987a4c8c8)

**Comment by cyfyifanchen** [comment]
I personally don't see the point of keep the color palette.
