### ISSUE TITLE
[BUG] orbstack compile failed

### ISSUE THREAD

**Issue by Zuckonit** [TEN-framework/TEN-Agent#464]
### Description

/app/agents/scripts/install_deps_and_build.sh: line 98:   125 Illegal instruction     /tmp/test
FATAL: unsupported platform.
       Please UNCHECK the 'Use Rosetta for x86_64/amd64 emulation on Apple Silicon' Docker Desktop setting if you're running on mac.

### Environment

mac m3 pro

### Steps to reproduce

docker-compose up
docker exec -it ten_agent_dev bash
task use

### Expected behavior

task use

### Severity

Critical

### Additional Information

/app/agents/scripts/install_deps_and_build.sh: line 98:   125 Illegal instruction     /tmp/test
FATAL: unsupported platform.
       Please UNCHECK the 'Use Rosetta for x86_64/amd64 emulation on Apple Silicon' Docker Desktop setting if you're running on mac.

**Comment by plutoless** [comment]
have you **UNCHECK the 'Use Rosetta for x86_64/amd64 emulation on Apple Silicon' Docker Desktop setting**?
