### ISSUE TITLE
[FEATURE] Why does the ten_agent_dev container interactively build the agent?

### ISSUE THREAD

**Issue by shaxiaozz** [TEN-framework/TEN-Agent#495]
### Description

![image](https://github.com/user-attachments/assets/80436868-561f-49ad-baea-e6d1bbd6d3b9)
Can steps 5 and 6 be integrated into the image? Whenever I need to update the environment variables, I need to re-execute ```docker compose up -d```, ```docker exec -it ten_agent_dev bash```, ```task use```, ```task run```, and the ```task use``` step takes a lot of time.

What is the reason for not doing this?

### Severity

Critical

**Comment by plutoless** [comment]
@shaxiaozz to update environment variables you don't need to re-create docker container. just run

```bash
source .env
```

this should reload all your env variables.
for our latest main branch, we have made this part of default setup for `task run`. so you just need to re-run `task run` in the future to make .env effective.
