### ISSUE TITLE
[BUG] ten_agent_demo Failed to connect/disconnect agent

### ISSUE THREAD

**Issue by shaxiaozz** [TEN-framework/TEN-Agent#497]
### Description

ten_agent_demo ui clicks Connect and the message Failed to connect/disconnect agent appears process property json failed
![image](https://github.com/user-attachments/assets/7f94534a-495e-46a2-9c05-00c66388d897)

Any of the items in the list will give an error like this

### Environment

Ubuntu 24.04.1 LTS 6.8.0-47-generic x86_64 Docker  Version:    27.3.1

### Steps to reproduce

According to the deployment in README
![image](https://github.com/user-attachments/assets/5e790474-edcf-4d90-8bf2-ed01dc841823)

### Expected behavior

I saw in the README that it is suggested to access http://localhost:3000, which is the port of the ten_agent_playground container. I can use this, but I hope to use the functions of the ten_agent_demo container at the same time, because I learned about it from this Youtube video: https://www.youtube.com/watch?v=ESEwLI1ygS0

The functions introduced here are based on ten_agent_demo, including the official https://agent.theten.ai/. So I hope to use the UI of ten_agent_demo, and I also hope that the UI of ten_agent_demo can work properly~
![image](https://github.com/user-attachments/assets/4d034064-f6f7-428f-a94f-114c25576cba)

### Severity

Critical

**Comment by plutoless** [comment]
check the doc here for how to run demo project.
https://doc.theten.ai/ten-agent/quickstart

note you will need to provide the keys yourself in .env

**Comment by shaxiaozz** [comment]
@plutoless Thanks for your guidance, but there seems to be a typo in the document. It should be: ```examples```
![image](https://github.com/user-attachments/assets/99be01e4-6755-4763-836c-89c1e504f272)

The following is the result of my direct copy and run
![image](https://github.com/user-attachments/assets/daffd439-7209-43f1-9d68-4836259c87d9)

**Comment by shaxiaozz** [comment]
@plutoless At the same time, is there any communication group, such as WeChat, TG?

**Comment by plutoless** [comment]
> @plutoless Thanks for your guidance, but there seems to be a typo in the document. It should be: `examples` ![image](https://private-user-images.githubusercontent.com/43721571/397589734-99be01e4-6755-4763-836c-89c1e504f272.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwMTIxMzMsIm5iZiI6MTczNTAxMTgzMywicGF0aCI6Ii80MzcyMTU3MS8zOTc1ODk3MzQtOTliZTAxZTQtNjc1NS00NzYzLTgzNmMtODljMWU1MDRmMjcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI0VDAzNDM1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1NGZiYmFjNGU4ZDliZjRlNWU4OWZhYmJiMjQ3ODJmYzk4Mzk5OGYxNWFhZTQ2ZWU5ZjUxNjAwNzc0YmQ3MjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.l6frVV9M_gbsZxvGMKk7sByzRWn8CuQD4yCBZSph8rE)
> 
> The following is the result of my direct copy and run ![image](https://private-user-images.githubusercontent.com/43721571/397589600-daffd439-7209-43f1-9d68-4836259c87d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwMTIxMzMsIm5iZiI6MTczNTAxMTgzMywicGF0aCI6Ii80MzcyMTU3MS8zOTc1ODk2MDAtZGFmZmQ0MzktNzIwOS00M2YxLTlkNjgtNDgzNjI1OWM4N2Q5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI0VDAzNDM1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlMzkzNDlhMjFiZThkZGNlODM1MTU5Y2EwMzc2MDRhN2ExYTk5MjFiODQ5YzFmNGRiNzg3NDdkNGFiY2YxNWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._z9ZQtTfdW22T_gRF63RjqBioSyEHoCCpgNhiJGieqA)

thanks! saw your pr. appreciate for the fix.
