### ISSUE TITLE
Media Device Options Missing on Docker-Deployed Page (Port 3000) In Server

### ISSUE THREAD

**Issue by teneous** [TEN-framework/TEN-Agent#541]
I deployed it using Docker Compose on a remote server (`192.168.101.243`). Then, I accessed port `3000` on the `243` server from my MacBook, but the page didn’t show options for selecting a microphone or camera. 

When I deployed it using Docker Compose on my local Mac, it successfully recognized the microphone on my Mac. Does this mean the docker image can only detect media devices on the host where it is deployed? However, I noticed that the example at `agent.theten.ai` can detect devices on my local machine. How is this achieved?

<img width="1442" alt="image" src="https://github.com/user-attachments/assets/0c600d7f-d45d-41b1-8607-7b1f4c9db098" />

**Comment by plutoless** [comment]
@teneous media device access requires https to work as it requires a safe environment.
if it's difficult to prepare a https host, you can try changing your chrome setting chrome://flags to change `Insecure origins treated as secure` option to add your ip address there.
or you can consider using codespace which provide https access by default. you may read the docs for how to setup a codespace [here](https://doc.theten.ai/ten-agent/overview-2/setting_up_development_inside_codespace)

**Comment by teneous** [comment]
> @teneous media device access requires https to work as it requires a safe environment. if it's difficult to prepare a https host, you can try changing your chrome setting chrome://flags to change `Insecure origins treated as secure` option to add your ip address there. or you can consider using codespace which provide https access by default. you may read the docs for how to setup a codespace [here](https://doc.theten.ai/ten-agent/overview-2/setting_up_development_inside_codespace)

Thanks， that helps a lot for me.
