### ISSUE TITLE
[Feature Request] Thinking about using Docker compose at the root of the project. 

### ISSUE THREAD

**Issue by cyfyifanchen** [TEN-framework/TEN-Agent#81]
`docker-compose.yml` has it's pros and cons. 

Someone in the community suggested that using `docker-compose` at the project root would be more convenient, allowing the environment to be set up with a simple `docker compose up -d`. They listed the benefits and, if consensus is reached, this approach could be considered for inclusion in the project root.

**Comment by Lensual** [comment]
对于想快速体验的开发者来说，docker compose来代替docker run会方便一些
1. 不依赖本地编译环境 node、go
  - 解决本地环境版本不一致
  - 对不熟悉使用特定工具链的人友好
2. 环境变量统一通过.env配置，`docker run` 单行命令过多变量可能会敲错

**Comment by cyfyifanchen** [comment]
supported.
